#line 2 "/home/russt/tmp/ibex-lib/build/src/parser/lexer.lex.cc"

#line 4 "/home/russt/tmp/ibex-lib/build/src/parser/lexer.lex.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ibex_create_buffer
#define yy_delete_buffer ibex_delete_buffer
#define yy_scan_buffer ibex_scan_buffer
#define yy_scan_string ibex_scan_string
#define yy_scan_bytes ibex_scan_bytes
#define yy_init_buffer ibex_init_buffer
#define yy_flush_buffer ibex_flush_buffer
#define yy_load_buffer_state ibex_load_buffer_state
#define yy_switch_to_buffer ibex_switch_to_buffer
#define yypush_buffer_state ibexpush_buffer_state
#define yypop_buffer_state ibexpop_buffer_state
#define yyensure_buffer_stack ibexensure_buffer_stack
#define yy_flex_debug ibex_flex_debug
#define yyin ibexin
#define yyleng ibexleng
#define yylex ibexlex
#define yylineno ibexlineno
#define yyout ibexout
#define yyrestart ibexrestart
#define yytext ibextext
#define yywrap ibexwrap
#define yyalloc ibexalloc
#define yyrealloc ibexrealloc
#define yyfree ibexfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define ibex_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer ibex_create_buffer
#endif

#ifdef yy_delete_buffer
#define ibex_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer ibex_delete_buffer
#endif

#ifdef yy_scan_buffer
#define ibex_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer ibex_scan_buffer
#endif

#ifdef yy_scan_string
#define ibex_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string ibex_scan_string
#endif

#ifdef yy_scan_bytes
#define ibex_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes ibex_scan_bytes
#endif

#ifdef yy_init_buffer
#define ibex_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer ibex_init_buffer
#endif

#ifdef yy_flush_buffer
#define ibex_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer ibex_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define ibex_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state ibex_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define ibex_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer ibex_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define ibexpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state ibexpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define ibexpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state ibexpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define ibexensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack ibexensure_buffer_stack
#endif

#ifdef yylex
#define ibexlex_ALREADY_DEFINED
#else
#define yylex ibexlex
#endif

#ifdef yyrestart
#define ibexrestart_ALREADY_DEFINED
#else
#define yyrestart ibexrestart
#endif

#ifdef yylex_init
#define ibexlex_init_ALREADY_DEFINED
#else
#define yylex_init ibexlex_init
#endif

#ifdef yylex_init_extra
#define ibexlex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra ibexlex_init_extra
#endif

#ifdef yylex_destroy
#define ibexlex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy ibexlex_destroy
#endif

#ifdef yyget_debug
#define ibexget_debug_ALREADY_DEFINED
#else
#define yyget_debug ibexget_debug
#endif

#ifdef yyset_debug
#define ibexset_debug_ALREADY_DEFINED
#else
#define yyset_debug ibexset_debug
#endif

#ifdef yyget_extra
#define ibexget_extra_ALREADY_DEFINED
#else
#define yyget_extra ibexget_extra
#endif

#ifdef yyset_extra
#define ibexset_extra_ALREADY_DEFINED
#else
#define yyset_extra ibexset_extra
#endif

#ifdef yyget_in
#define ibexget_in_ALREADY_DEFINED
#else
#define yyget_in ibexget_in
#endif

#ifdef yyset_in
#define ibexset_in_ALREADY_DEFINED
#else
#define yyset_in ibexset_in
#endif

#ifdef yyget_out
#define ibexget_out_ALREADY_DEFINED
#else
#define yyget_out ibexget_out
#endif

#ifdef yyset_out
#define ibexset_out_ALREADY_DEFINED
#else
#define yyset_out ibexset_out
#endif

#ifdef yyget_leng
#define ibexget_leng_ALREADY_DEFINED
#else
#define yyget_leng ibexget_leng
#endif

#ifdef yyget_text
#define ibexget_text_ALREADY_DEFINED
#else
#define yyget_text ibexget_text
#endif

#ifdef yyget_lineno
#define ibexget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno ibexget_lineno
#endif

#ifdef yyset_lineno
#define ibexset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno ibexset_lineno
#endif

#ifdef yywrap
#define ibexwrap_ALREADY_DEFINED
#else
#define yywrap ibexwrap
#endif

#ifdef yyalloc
#define ibexalloc_ALREADY_DEFINED
#else
#define yyalloc ibexalloc
#endif

#ifdef yyrealloc
#define ibexrealloc_ALREADY_DEFINED
#else
#define yyrealloc ibexrealloc
#endif

#ifdef yyfree
#define ibexfree_ALREADY_DEFINED
#else
#define yyfree ibexfree
#endif

#ifdef yytext
#define ibextext_ALREADY_DEFINED
#else
#define yytext ibextext
#endif

#ifdef yyleng
#define ibexleng_ALREADY_DEFINED
#else
#define yyleng ibexleng
#endif

#ifdef yyin
#define ibexin_ALREADY_DEFINED
#else
#define yyin ibexin
#endif

#ifdef yyout
#define ibexout_ALREADY_DEFINED
#else
#define yyout ibexout
#endif

#ifdef yy_flex_debug
#define ibex_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug ibex_flex_debug
#endif

#ifdef yylineno
#define ibexlineno_ALREADY_DEFINED
#else
#define yylineno ibexlineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[288] =
    {   0,
        0,    0,   58,   56,   50,   51,   51,   56,   56,   56,
       56,   47,   56,   56,   54,   56,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       50,   51,    0,   43,   46,   45,    0,   48,   45,   47,
        0,   55,   52,   53,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   31,   13,   44,
       44,   42,   44,   41,   44,   44,   44,   44,   44,   44,

        0,    0,    0,   48,   45,   47,    0,   45,   44,   44,
       44,   44,   38,   39,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   11,   44,   44,   44,   44,   44,
       30,   44,   15,   44,   12,   44,   44,   32,   44,    7,
       33,    8,   44,   44,   44,   16,   44,   35,   34,   17,
       44,    0,   45,   49,   47,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   18,
       19,   20,   44,   28,   44,   21,    6,   44,   44,   44,
       44,   44,   44,   10,   22,   14,   23,   44,   47,   37,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,

       44,   44,   24,   25,    9,   26,   44,   27,   44,   44,
       44,   44,   44,   44,   45,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   36,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   45,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   29,   44,   44,   44,   45,   44,   44,   44,   44,
        4,    5,   44,   44,   44,   44,   44,   44,   44,   44,
       45,    1,   44,   44,   44,   44,    2,   44,   44,   45,
       44,   44,    3,   44,   45,   40,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    1,
        1,    7,    8,    1,    9,   10,   11,   12,   12,   13,
       12,   12,   12,   12,   12,   12,   12,   14,    1,   15,
       16,   17,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   25,   25,   27,   28,   29,   30,   31,
       25,   32,   33,   34,   35,   36,   25,   25,   25,   37,
        1,    1,    1,    1,   25,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   25,   25,   47,   48,   49,
       50,   51,   52,   53,   54,   55,   56,   57,   25,   58,
       25,   59,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[293] =
    {   0,
        0,    0,  390,  391,  387,  391,  385,  382,    0,   48,
       55,   55,  370,  369,  391,  368,    0,   41,   34,   40,
       40,   45,   54,   51,   56,   46,  341,   37,  336,   46,
       52,  332,  331,   42,  329,   60,  336,   57,  339,  338,
      373,  391,  369,  368,    0,   65,  365,    0,   98,  102,
      108,  391,  391,  391,    0,  347,  326,  340,  319,  346,
      325,  333,  335,  310,  313,  332,  311,  327,  305,  323,
      301,  323,  301,  299,  302,  305,  312,  305,  302,  301,
       27,  303,  304,  293,  293,  289,  292,   75,    0,  282,
       78,    0,  286,    0,  283,   79,  284,   74,  287,  282,

      123,  327,  322,    0,  121,  129,  125,  133,  306,  285,
      297,  275,    0,    0,  308,  287,  300,  279,  306,  285,
      287,  265,  294,  273,    0,  264,  268,  267,  269,  267,
        0,  259,  267,  268,    0,  260,  269,    0,  266,    0,
        0,  261,  268,  249,  255,  258,  247,    0,    0,  256,
      254,  135,  137,  391,  141,  270,  249,  263,  241,  261,
      239,  265,  244,  263,  242,  257,  235,  269,  248,  240,
      239,  111,  234,    0,  227,    0,    0,  228,  225,  235,
      230,  229,  223,    0,    0,    0,    0,  237,  145,    0,
      111,  114,  248,  227,  246,  225,  248,  227,  239,  218,

      247,  226,    0,    0,    0,    0,  121,    0,  218,  221,
      216,  219,  211,  220,  152,  229,  239,  207,  217,  224,
      203,  215,  192,  216,  194,    0,  221,  200,  197,  207,
      194,  190,  183,  186,  193,  156,  205,  212,  182,  190,
      206,  185,  211,  188,  198,  175,  194,  173,  159,  167,
      163,    0,  168,  167,  166,  160,  173,  176,  150,  154,
        0,    0,  169,  147,  166,  143,  142,  146,  140,  138,
      165,    0,  157,  135,  152,  130,    0,  125,  122,  169,
      128,  106,    0,   72,  176,    0,  391,  218,  102,  220,
      224,  228

    } ;

static const flex_int16_t yy_def[293] =
    {   0,
      287,    1,  287,  287,  287,  287,  287,  288,  289,  287,
      287,  287,  287,  287,  287,  287,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      287,  287,  288,  288,  289,  287,  291,  292,  287,  287,
      287,  287,  287,  287,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      287,  291,  291,  292,  287,  287,  287,  287,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  287,  287,  287,  287,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  287,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  287,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  287,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  287,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      287,  290,  290,  290,  290,  290,  290,  290,  290,  287,
      290,  290,  290,  290,  287,  290,    0,  287,  287,  287,
      287,  287

    } ;

static const flex_int16_t yy_nxt[451] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,    4,    4,   10,
       11,   12,   12,   13,   14,   15,   16,   17,   18,   19,
       17,   20,   21,   17,   17,   17,   17,   22,   17,   17,
       23,   24,   17,   17,   17,   25,   17,   26,   27,   28,
       29,   30,   31,   17,   17,   32,   33,   34,   17,   35,
       36,   17,   37,   38,   39,   17,   40,   17,   17,   46,
       46,   47,   56,   58,   49,   48,   50,   50,   60,   62,
       66,   68,   70,   72,   63,  132,   46,   46,   79,   90,
      133,   80,   57,   59,   74,   75,   81,   91,   61,   64,
       67,   69,   71,   73,   83,   65,   51,   93,   85,   76,

       77,   86,   96,   84,   45,   94,  101,   87,   97,  105,
      105,   49,   98,  106,  106,  107,  107,  138,  141,  108,
      108,  148,  145,  205,  149,  286,  142,  146,  216,  139,
      152,  152,  105,  105,  153,  153,  108,  108,   49,  101,
      155,  155,  217,   51,  108,  108,  153,  153,  153,  153,
       49,  218,  189,  189,   49,  206,  215,  215,  229,  286,
      286,   49,  101,  236,  236,   49,  219,  256,  256,   49,
       51,  271,  271,  230,   49,  283,  280,  280,   49,  284,
      285,  285,   51,  283,  283,   49,   51,  285,  285,  282,
      281,  277,  279,  101,  278,  272,  277,  101,  277,  276,

      275,  101,  274,  272,  273,  272,  101,  270,  269,  262,
      101,  261,  268,  267,  266,  265,  264,  101,   43,  263,
       43,   43,   55,   55,  102,  102,  102,  102,  104,  262,
      104,  104,  262,  261,  261,  260,  259,  258,  257,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  235,  226,
      234,  233,  232,  231,  228,  227,  226,  226,  225,  224,
      223,  222,  221,  220,  214,  213,  212,  211,  210,  209,
      208,  207,  190,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  190,  188,

      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,
      157,  156,  154,  103,  151,  150,  147,  144,  143,  140,
      137,  114,  136,  135,  113,  134,  131,  130,  129,  128,
      127,  126,  125,  124,  123,  122,  121,  120,  119,  118,
      117,  116,  114,  115,  114,  113,  113,  112,  111,  110,
      109,  103,   44,   44,   41,  100,   99,   95,   92,   89,
       88,   82,   78,   54,   53,   52,   44,   42,   41,  287,
        3,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287
    } ;

static const flex_int16_t yy_chk[451] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   10,
       10,   11,   18,   19,   12,   11,   12,   12,   20,   21,
       22,   23,   24,   25,   21,   81,   46,   46,   28,   34,
       81,   28,   18,   19,   26,   26,   28,   34,   20,   21,
       22,   23,   24,   25,   30,   21,   12,   36,   31,   26,

       26,   31,   38,   30,  289,   36,   46,   31,   38,   49,
       49,   50,   38,   50,   50,   51,   51,   88,   91,   51,
       51,   98,   96,  172,   98,  284,   91,   96,  191,   88,
      101,  101,  105,  105,  101,  101,  107,  107,  106,   49,
      106,  106,  191,   50,  108,  108,  152,  152,  153,  153,
      155,  192,  155,  155,  189,  172,  189,  189,  207,  282,
      281,  215,  105,  215,  215,  236,  192,  236,  236,  256,
      106,  256,  256,  207,  271,  279,  271,  271,  280,  278,
      280,  280,  155,  276,  275,  285,  189,  285,  285,  274,
      273,  270,  269,  215,  268,  267,  266,  236,  265,  264,

      263,  256,  260,  259,  258,  257,  271,  255,  254,  253,
      280,  251,  250,  249,  248,  247,  246,  285,  288,  245,
      288,  288,  290,  290,  291,  291,  291,  291,  292,  244,
      292,  292,  243,  242,  241,  240,  239,  238,  237,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  214,  213,
      212,  211,  210,  209,  202,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  188,  183,  182,  181,  180,  179,
      178,  175,  173,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  151,

      150,  147,  146,  145,  144,  143,  142,  139,  137,  136,
      134,  133,  132,  130,  129,  128,  127,  126,  124,  123,
      122,  121,  120,  119,  118,  117,  116,  115,  112,  111,
      110,  109,  103,  102,  100,   99,   97,   95,   93,   90,
       87,   86,   85,   84,   83,   82,   80,   79,   78,   77,
       76,   75,   74,   73,   72,   71,   70,   69,   68,   67,
       66,   65,   64,   63,   62,   61,   60,   59,   58,   57,
       56,   47,   44,   43,   41,   40,   39,   37,   35,   33,
       32,   29,   27,   16,   14,   13,    8,    7,    5,    3,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
#line 2 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"

//============================================================================
//                                  I B E X
// File        : Flex input for Ibex lexer
// Author      : Gilles Chabert
// Copyright   : Ecole des Mines de Nantes (France)
// License     : See the LICENSE file
// Created     : Jun 12, 2012
// Last Update : Jun 12, 2012
//============================================================================

// fix isatty call for MSVC
#ifdef _WIN32
#include <io.h>
#define isatty _isatty
#endif

#include "ibex_Interval.h"
#include "ibex_Expr.h"
#include "ibex_ExprOperators.h"
#include "ibex_SyntaxError.h"
#include "ibex_P_NumConstraint.h"
#include "ibex_P_Struct.h"

#include "parser.tab.hh"

#include <stdlib.h>
#include <stack>
#include <vector>
#include <stdint.h>
#include <cassert>

int ibex_lineno = 1;

using namespace ibex;
using namespace ibex::parser;

#line 934 "/home/russt/tmp/ibex-lib/build/src/parser/lexer.lex.cc"
#line 935 "/home/russt/tmp/ibex-lib/build/src/parser/lexer.lex.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 41 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"





#line 1158 "/home/russt/tmp/ibex-lib/build/src/parser/lexer.lex.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 288 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 391 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_CONST; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 47 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_VARS; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 48 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_PARAM; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_FUNCTION; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_MINIMIZE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 52 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_DIFF; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_MAX; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_MIN; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_ATAN2; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_SIGN; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_ABS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_EXPO; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 59 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_LOG; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 60 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_SQRT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 61 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_COS; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 62 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_SIN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 63 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_TAN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 64 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_ACOS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 65 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_ASIN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 66 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_ATAN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 67 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_COSH; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 68 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_SINH; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 69 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_TANH; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 70 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_ACOSH; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 71 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_ASINH; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 72 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_ATANH; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 73 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_FLOOR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 74 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_CEIL; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 75 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_INTEGER; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 76 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_CHI; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 77 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_IN;  }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 78 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_INF; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 79 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_MID; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 80 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_SUP; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 81 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_SUM; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 83 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_RETURN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 84 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_BEGIN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 85 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_END;  }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 86 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_FOR;  }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 88 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_CTRS; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 90 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_PI; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 91 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_INFINITY; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 92 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ ibexlval.str = (char*) malloc(strlen(ibextext)-1);
                                   /* copy while removing quotes */
                                   strncpy(ibexlval.str,&ibextext[1],strlen(ibextext)-2);
                                   ibexlval.str[strlen(ibextext)-2]='\0';
                                   return TK_STRING;
                                 }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 98 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ ibexlval.str = (char*) malloc(strlen(ibextext)+1);
                                   strcpy(ibexlval.str,ibextext);
                                   if (pstruct->scopes.empty())
                                      // happens when the program starts by an identifier (an error). 
  									  // The lexer tries to retreive this identifier from the scope, which has not
  									  // been created yet -> seg fault
  									  return TK_NEW_SYMBOL;
  								   else 
  								      try {
  								        ExprGenericUnaryOp::get_eval(ibextext); 
  								        return TK_UNARY_OP;
  								      } catch(SyntaxError&) {
  								        try {
  								          ExprGenericBinaryOp::get_eval(ibextext); 
  								          return TK_BINARY_OP;
  								        } catch(SyntaxError&) {
                                          return pstruct->scopes.top().token(ibextext);
                                        }
                                      }
                                 }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 118 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{
                                   ibexlval.real = atof(ibextext); return TK_FLOAT;
                                 }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 121 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ // read a double from its exact hexadecimal representation
                                   assert(sizeof(double)==8);
                                   uint64_t u = strtoll(&ibextext[1],NULL,16); // note: we remove the '#' character
                                   memcpy(&ibexlval.real, &u, 8);
                                   return TK_FLOAT;
                                 }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 127 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ ibexlval.itg = atoi(ibextext); return TK_INT_CST; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 129 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ /* C++-like comments. Note: '.' also accepts CR characters (not LF).*/ }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 130 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ /* C-like comments */
                                   /*strtok (ibextext,"\n");
                                   while (strtok(NULL,"\n")) ++ibex_lineno; */
                                   char* s=ibextext;
                                   while ((s=strpbrk(s,"\n"))) { s+=sizeof(char); ++ibex_lineno; }
                                 }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 137 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ /* skipping spaces */ }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 139 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ ++ibex_lineno; /* counting end of lines (either CR, LF or CRLF depending on the encoding) */
					               /* the line count is OK if different conventions are not mixed in the same file (should be ok). */
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 143 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_LEQ; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 144 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_GEQ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 145 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_EQU; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 146 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return TK_ASSIGN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 147 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ return ibextext [0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 148 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
{ YY_NEW_FILE; yyterminate(); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 150 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"
ECHO;
	YY_BREAK
#line 1544 "/home/russt/tmp/ibex-lib/build/src/parser/lexer.lex.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 288 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 288 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 287);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 150 "/home/russt/tmp/ibex-lib/src/parser/lexer.l"


int ibexwrap () { return 1; }

extern int ibexparse();

void ibexparse_string(const char* syntax) {

	// We have to delete the buffer created (new_buff) at the end of
	// this function otherwise the next call to ibexparse_string(...)
	// will create another buffer and the first one would leak in memory.
	// But, then, if we instead parse a file (not a string) right after this
	// call, a memory fault occurs because YY_CURRENT_BUFFER (which points
	// to new_buff) has been destroyed.
	//
	// I tried to save YY_CURRENT_BUFFER and restore its old value
	// with ibex_switch_to_buffer(...) at the end, but it did not work.

	// So I force here deletion of YY_CURRENT_BUFFER
	// and then recreate the buffer using ibexrestart(...) at the end.

	ibex_delete_buffer(YY_CURRENT_BUFFER);

	// copy string into a new buffer and switch buffers
	YY_BUFFER_STATE new_buff = ibex_scan_string (syntax);

	// analyze the string
	try {
	  ibexparse();
	} catch(SyntaxError& e) {
	  // delete the new buffer
	  ibex_delete_buffer(new_buff);
	  ibexrestart(stdin);
      throw(e);
	}

	// delete the new buffer
	ibex_delete_buffer(new_buff);

	// necessary, otherwise provokes a memory fault when another
	// file is read after (this fault does not occur if we parse a system
	// from a string again). I also tried to save YY_CURRENT_BUFFER
	// and restore the old buffer with ibex_switch_to_buffer(...) but
	// it did not work.
	ibexrestart(stdin);
}

//"/""*"*([^*]|("*")+[^/])"*"*"/"    { /* C-like comments */ }

